name: CI

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: fmt, test, and lint
        run: |
          make fmt & FMT=$!
          make test & TEST=$!
          make lint
          wait $FMT
          wait $TEST
